openapi: 3.0.0
info:
  title: Text Version Control API
  version: 1.0.0
tags:
  - name: user
  - name: repository
  - name: branch
  - name: commit
  - name: file
  - name: merge
  - name: graph
servers:
  - url: http://localhost:8080/api
paths:
  /user:
    get:
      tags: [user]
      summary: ユーザー一覧取得
      responses:
        '200':
          description: ユーザー一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
    post:
      tags: [user]
      summary: ユーザー作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: 作成結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
    delete:
      tags: [user]
      summary: ユーザー削除
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 削除結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
  /repository:
    get:
      tags: [repository]
      summary: リポジトリ一覧取得
      parameters:
        - in: query
          name: owner_id
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: リポジトリ一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  repositories:
                    type: array
                    items:
                      $ref: '#/components/schemas/Repository'
    post:
      tags: [repository]
      summary: リポジトリ作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                owner_id:
                  type: integer
      responses:
        '200':
          description: 作成結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
    delete:
      tags: [repository]
      summary: リポジトリ削除
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 削除結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
  /branch:
    get:
      tags: [branch]
      summary: ブランチ一覧取得
      parameters:
        - in: query
          name: repository_id
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: ブランチ一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  branches:
                    type: array
                    items:
                      $ref: '#/components/schemas/Branch'
    post:
      tags: [branch]
      summary: ブランチ作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                repository_id:
                  type: integer
      responses:
        '200':
          description: 作成結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
    delete:
      tags: [branch]
      summary: ブランチ削除
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 削除結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
    put:
      tags: [branch]
      summary: ブランチのhead_commit_id付け替え
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                commit_id:
                  type: integer
      responses:
        '200':
          description: 更新結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
  /commit:
    get:
      tags: [commit]
      summary: コミット一覧取得
      parameters:
        - in: query
          name: branch_id
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: コミット一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  commits:
                    type: array
                    items:
                      $ref: '#/components/schemas/Commit'
    post:
      tags: [commit]
      summary: コミット作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                branch_id:
                  type: integer
                message:
                  type: string
                author_id:
                  type: integer
                content:
                  type: string
      responses:
        '200':
          description: 作成結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
    delete:
      tags: [commit]
      summary: コミット削除
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 削除結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
  /file:
    get:
      tags: [file]
      summary: ファイル表示
      parameters:
        - in: query
          name: repository_id
          schema:
            type: integer
          required: false
        - in: query
          name: branch_id
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: ファイル一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      $ref: '#/components/schemas/File'
  /merge:
    post:
      tags: [merge]
      summary: ブランチのマージ
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                branch_id:
                  type: integer
                target_branch_id:
                  type: integer
      responses:
        '200':
          description: マージ結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  conflict:
                    type: boolean
                  message:
                    type: string
  /graph:
    get:
      tags: [graph]
      summary: コミットグラフ取得
      parameters:
        - in: query
          name: repository_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: グラフデータ
          content:
            application/json:
              schema:
                type: object
                properties:
                  nodes:
                    type: array
                    items:
                      type: object
                  edges:
                    type: array
                    items:
                      type: object
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
    Repository:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        owner_id:
          type: integer
    Branch:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        repository_id:
          type: integer
        head_commit_id:
          type: integer
    Commit:
      type: object
      properties:
        id:
          type: integer
        repository_id:
          type: integer
        author_id:
          type: integer
        message:
          type: string
        parent_commit_id:
          type: integer
        parent_commit_id_2:
          type: integer
        created_at:
          type: string
    File:
      type: object
      properties:
        id:
          type: integer
        commit_id:
          type: integer
        filename:
          type: string
        content:
          type: string
    Success:
      type: object
      properties:
        success:
          type: boolean
